- name: Debug information
  debug:
    msg: "Hostname task is about to be executed."

- name: Get hostname
  command: hostname
  register: hostname_result

- name: Display hostname
  debug:
    var: hostname_result.stdout
