---
- name: Handle Git Tags
  hosts: alpha:playground
  gather_facts: no
  tasks:
    - name: Get Git Tags
      git:
        repo: "{{ app_repo }}"
        clone: no
      register: git_tags

    - name: Determine Tag
      set_fact:
        selected_tag: "{{ item }}"
      with_items: "{{ git_tags.stdout_lines }}"
      when: selected_tag is not defined and (item.endswith('-alpha') or item.endswith('-playground'))

    - name: Copy File Based on Tag
      copy:
        src: "/tmp/{{ selected_tag }}"
        dest: "/tmp/{{ selected_tag }}"
      delegate_to: "{{ inventory_hostname }}"
      when: selected_tag is defined
