---
- name: Get Git Tags
  shell: git ls-remote --tags "{{ app_repo }}"
  register: git_tags

- name: Filter Hostnames
  debug:
    var: item
  loop: "{{ ansible_play_hosts_all }}"
  when: ("{{ git_tag }}-playground" in git_tags.stdout and '-playground' in item) or ("{{ git_tag }}-alpha" in git_tags.stdout and '-alpha' in item)
