---
- name: Get Git Tags
  shell: git ls-remote --tags "{{ app_repo }}"
  register: git_tags

- name: Filter Alpha Hostnames
  debug:
    var: item
  loop: "{{ ansible_play_hosts_all }}"
  when: "'-alpha' in item and ('{{ git_tag }}' in git_tags.stdout or '-playground' in git_tags.stdout)"

- name: Filter Playground Hostnames
  debug:
    var: item
  loop: "{{ ansible_play_hosts_all }}"
  when: "'-playground' in item and ('{{ git_tag }}' in git_tags.stdout or '-alpha' in git_tags.stdout)"
