---
- name: Get Hostname
  hosts: "{{ deployment_environment }}"
  gather_facts: false
  tasks:
    - name: Get hostname
      command: hostname
      register: hostname_result

    - name: Display hostname
      debug:
        var: hostname_result.stdout
