---
- name: Deploy application
  hosts: all
  gather_facts: false
  vars_prompt:
    - name: git_tag
      prompt: "Enter the Git tag to deploy"
      private: no
      default: ""
    - name: app_repo
      prompt: "Enter the application repository URL"
      private: no
      default: "https://github.com/aushlya95/alpha.lambdax.san.git"

  tasks:
    - name: Determine deployment environment
      set_fact:
        deployment_environment: "dev"
      when: git_tag.endswith('-alpha')

    - name: Determine deployment environment
      set_fact:
        deployment_environment: "stage"
      when: git_tag.endswith('-playground')

    - name: Display deployment environment
      debug:
        var: deployment_environment

- name: Clone application repository and deploy
  hosts: "{{ deployment_environment }}"
  become: yes

  roles:
    - ansible-tag-deployment
  tasks:
    - name: Clone application repository
      git:
        repo: "{{ app_repo }}"
        dest: /tmp
        version: "{{ git_tag }}"
      register: clone_result

    - name: Display clone result
      debug:
        var: clone_result

    # Additional deployment tasks for your application
