---
- name: Clone application repository
  git:
    repo: "{{ app_repo }}"
    dest: /tmp
    version: "{{ git_tag }}"
  register: clone_result

- name: Display clone result
  debug:
    var: clone_result

# Additional deployment tasks for your application
