---
- name: Handle Git Tags and Retrieve Hostnames
  hosts: alpha:playgroun
  gather_facts: no
  tasks:
    - name: Get Hostname
      command: hostname
      register: hostname_result
      when: selected_tag is defined

    - name: Display Hostname
      debug:
        var: hostname_result.stdout
