---
- name: Get Hostname
  hosts: all # Specify your target hosts here
  become: yes
  tasks:
    - name: Get the hostname of the servers
      command: hostname
      register: hostname_register

    - name: Display Hostname
      debug:
        var: hostname_register.stdout
