---
- name: Get Hostname
  hosts: alpha:playground  # Specify your target hosts here
  gather_facts: yes
  tasks:
    - name: Get Hostname
      command: hostname
      register: hostname_result

    - name: Display Hostname
      debug:
        var: hostname_result.stdout
