---
- name: Hostname | Setting up hostname
  become: true
  tasks:
    - name: Get the hostname of the servers
      shell: hostname
      register: hostname_register

    - name: Display Hostname
      debug:
        var: hostname_register.stdout
