---
- hosts: all
  gather_facts: false
  tasks:
    - name: Get hostname
      shell: hostname
      register: hostname_result

    - name: Display hostname
      debug:
        var: hostname_result.stdout
